<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-4E9IK45" failures="1" tests="6" name="Test" time="124.737" errors="0" timestamp="2022-09-28T14:25:50 IST">
  <testcase classname="com.test.test" name="verifyBackpack" time="2.221"/>
  <testcase classname="com.test.test" name="verifyBikelight" time="2.276"/>
  <testcase classname="com.test.test" name="verifyTshirt" time="2.098"/>
  <testcase classname="com.test.test" name="verifyJacket" time="0.141">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory-item.html?id=5] but found [https://www.saucedemo.com/inventory-item.html?id=]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory-item.html?id=5] but found [https://www.saucedemo.com/inventory-item.html?id=]
at com.test.test.verifyJacket(test.java:99)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyJacket -->
  <testcase classname="com.test.test" name="verifyOnesie" time="2.372"/>
  <testcase classname="com.test.test" name="verifyRedTshirt" time="2.133"/>
</testsuite> <!-- Test -->
